spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tk.chess.com
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

token:
  signing:
    key: .