spring:
  datasource:
    url: jdbc:postgresql://ep-noisy-hat-a2ufyuso-pooler.eu-central-1.aws.neon.tech/tk.chess.com?sslmode=require
    username: postgres
    password: npg_gM8mAszltEO7
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  email:
    userName: tk.chess.school@gmail.com
    password: .
  front:
    url: https://tk-chess-com-i4rw.onrender.com

server:
  port: 8080

token:
  signing:
    key: ee4ef586e804e9660287ff112513fd3cb82a0e8ff9775592e812863ef337b076

google:
  client-id: 756752521081-p0du6951j4598agcdbaoumt3dsv6ikup.apps.googleusercontent.com